# Diário (31/07/2025)
**Hoje:** 
1. Jupyter-lab rodando no servidor
2. Ambiente pronto
3. Evo2 instalado
```shell
pixi add --pypi evo2
```
- Erro encontrado
```
  File "/home/jaoliveira/embeddings/.pixi/envs/default/lib/python3.12/site-packages/transformer_engine/common/__init__.py", line 168, in load_framework_extension
    solib = importlib.util.module_from_spec(spec)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: /home/jaoliveira/embeddings/.pixi/envs/default/lib/python3.12/site-packages/transformer_engine/wheel_lib/transformer_engine_torch.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationESs
```

**Amanhã:** 
- [x] Identificar e resolver os erros.
- [x] Detalhar erro e solução no diário.
- [x] Terminar de configurar o ambiente.
- [ ] Resolver o erro do evo2
- [ ] Escrever o script para a vetorização dos nucleotídeos.
- [ ] Continuar a processar os dados.
